/**
 * Centralized Lucide icon registry for sidebar navigation.
 * Single source for AppSidebar and AdminSidebar icon resolution.
 */

import {
  Activity,
  ArrowLeftRight,
  BadgeDollarSign,
  BarChart,
  BarChart2,
  BarChart3,
  Binary,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  CheckCircle2,
  ClipboardList,
  Cpu,
  CreditCard,
  Database,
  FileStack,
  FileText,
  FolderOpen,
  FolderTree,
  Gauge,
  GitBranch,
  Globe,
  HandHeart,
  Heart,
  HelpCircle,
  Inbox,
  Landmark,
  Layers,
  LayoutDashboard,
  LineChart,
  ListTodo,
  Mail,
  MessageSquare,
  Mic,
  Network,
  PenTool,
  Plug,
  Presentation,
  RefreshCw,
  Rocket,
  ScanSearch,
  ScrollText,
  Search,
  SearchCode,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  Ship,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Target,
  Ticket,
  TrendingUp,
  Upload,
  UserCog,
  UserPlus,
  Users,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const navIconMap = {
  Activity,
  ArrowLeftRight,
  BadgeDollarSign,
  BarChart,
  BarChart2,
  BarChart3,
  Binary,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  CheckCircle2,
  ClipboardList,
  Cpu,
  CreditCard,
  Database,
  FileStack,
  FileText,
  FolderOpen,
  FolderTree,
  Gauge,
  GitBranch,
  Globe,
  HandHeart,
  Heart,
  HelpCircle,
  Inbox,
  Landmark,
  Layers,
  LayoutDashboard,
  LineChart,
  ListTodo,
  Mail,
  MessageSquare,
  Mic,
  Network,
  PenTool,
  Plug,
  Presentation,
  RefreshCw,
  Rocket,
  ScanSearch,
  ScrollText,
  Search,
  SearchCode,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  Ship,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Target,
  Ticket,
  TrendingUp,
  Upload,
  UserCog,
  UserPlus,
  Users,
  Zap,
} satisfies Record<string, LucideIcon>;

export type NavIconName = keyof typeof navIconMap;

const warnedIcons = new Set<string>();

export function resolveNavIcon(iconName: string): LucideIcon {
  const icon = navIconMap[iconName as NavIconName];
  if (icon) return icon;

  if (import.meta.env.DEV && !warnedIcons.has(iconName)) {
    warnedIcons.add(iconName);
    console.warn(`[navIcons] Unknown navigation icon "${iconName}" — falling back to LayoutDashboard`);
  }

  return LayoutDashboard;
}
