/**
 * Generates idempotent nonprofit seed SQL from nonprofitDemoData.ts.
 * Run: npm run seed:nonprofit:generate
 */

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse, format } from "date-fns";
import {
  DEMO_MEMBERS,
  DEMO_VOLUNTEERS,
  DEMO_CAMPAIGNS,
  DEMO_DONATIONS_RECENT,
  DEMO_MANAGED_EVENTS,
  DEMO_PROGRAMS,
} from "../src/shared/data/nonprofitDemoData.ts";

const SEED_DIR = join(import.meta.dirname, "../supabase/seed");
const DATE_FMT = "MMM d, yyyy";

const AUTH_GUARD = `-- Abort if no auth users (created_by subquery would be NULL)
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM auth.users) = 0 THEN
    RAISE EXCEPTION 'SEED ABORTED: No users in auth.users. Sign up via the app first.';
  END IF;
END $$;

`;

/** Deterministic UUID from demo id (stable across re-runs). */
export function seedUuid(demoId: string): string {
  const hash = createHash("sha256").update(`nonprofitctdemo-seed:${demoId}`).digest("hex");
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    `4${hash.slice(13, 16)}`,
    `8${hash.slice(17, 20)}`,
    hash.slice(20, 32),
  ].join("-");
}

function sqlStr(value: string | null | undefined): string {
  if (value == null) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlBool(value: boolean): string {
  return value ? "TRUE" : "FALSE";
}

function sqlNum(value: number | null | undefined): string {
  if (value == null) return "NULL";
  return String(value);
}

function sqlTextArray(values: string[]): string {
  if (values.length === 0) return "ARRAY[]::text[]";
  return `ARRAY[${values.map((v) => sqlStr(v)).join(", ")}]`;
}

function parseDemoDate(raw: string, context: string): string {
  const parsed = parse(raw, DATE_FMT, new Date());
  if (Number.isNaN(parsed.getTime())) {
    throw new Error(`Failed to parse date "${raw}" for ${context} (expected ${DATE_FMT})`);
  }
  return format(parsed, "yyyy-MM-dd");
}

function parseDemoTimestamp(raw: string, context: string): string {
  const date = parseDemoDate(raw, context);
  return `${date} 12:00:00+00`;
}

function fileHeader(name: string): string {
  return `-- ============================================================
-- SEED: ${name}
-- AUTO-GENERATED by scripts/generate-nonprofit-seed.ts
-- Source: src/shared/data/nonprofitDemoData.ts
-- Safe to re-run (idempotent upserts on fixed seed UUIDs).
-- Prerequisite: at least one row in auth.users
-- ============================================================

${AUTH_GUARD}`;
}

function generateMembersSql(): string {
  const ids = DEMO_MEMBERS.map((m) => seedUuid(m.id));
  const lines: string[] = [
    fileHeader("Nonprofit Members"),
    `DELETE FROM public.nonprofit_members WHERE id IN (${ids.map((id) => `'${id}'`).join(", ")});`,
    "",
    "INSERT INTO public.nonprofit_members (",
    "  id, created_by, name, email, phone, tier, status, join_date, renewal_date, employer, interests",
    ") VALUES",
  ];

  const rows = DEMO_MEMBERS.map((m, i) => {
    const parts = [
      `'${seedUuid(m.id)}'`,
      "(SELECT id FROM auth.users ORDER BY created_at LIMIT 1)",
      sqlStr(m.name),
      sqlStr(m.email),
      sqlStr(m.phone ?? null),
      sqlStr(m.tier),
      sqlStr(m.status),
      sqlStr(parseDemoDate(m.joinDate, m.id)),
      sqlStr(parseDemoDate(m.renewalDate, m.id)),
      sqlStr(m.employer ?? null),
      sqlTextArray(m.interests),
    ];
    const suffix = i < DEMO_MEMBERS.length - 1 ? "," : "";
    return `  (${parts.join(", ")})${suffix}`;
  });

  lines.push(...rows);
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET",
    "  name = EXCLUDED.name,",
    "  email = EXCLUDED.email,",
    "  phone = EXCLUDED.phone,",
    "  tier = EXCLUDED.tier,",
    "  status = EXCLUDED.status,",
    "  join_date = EXCLUDED.join_date,",
    "  renewal_date = EXCLUDED.renewal_date,",
    "  employer = EXCLUDED.employer,",
    "  interests = EXCLUDED.interests,",
    "  updated_at = now();",
    ""
  );
  return lines.join("\n");
}

function generateVolunteersSql(): string {
  const volunteerIds = DEMO_VOLUNTEERS.map((v) => seedUuid(v.id));
  const shiftIds = DEMO_VOLUNTEERS.flatMap((v) => v.shifts.map((s) => seedUuid(s.id)));

  const lines: string[] = [
    fileHeader("Nonprofit Volunteers + Shifts"),
    `DELETE FROM public.nonprofit_volunteer_shifts WHERE id IN (${shiftIds.map((id) => `'${id}'`).join(", ")});`,
    `DELETE FROM public.nonprofit_volunteers WHERE id IN (${volunteerIds.map((id) => `'${id}'`).join(", ")});`,
    "",
    "INSERT INTO public.nonprofit_volunteers (",
    "  id, created_by, name, email, phone, skills, availability, total_hours, joined_date, is_also_donor, donor_total_giving",
    ") VALUES",
  ];

  const volunteerRows = DEMO_VOLUNTEERS.map((v, i) => {
    const parts = [
      `'${seedUuid(v.id)}'`,
      "(SELECT id FROM auth.users ORDER BY created_at LIMIT 1)",
      sqlStr(v.name),
      sqlStr(v.email),
      "NULL",
      sqlTextArray(v.skills),
      sqlTextArray(v.availability),
      sqlNum(v.totalHours),
      sqlStr(parseDemoDate(v.joinedDate, v.id)),
      sqlBool(v.isAlsoDonor),
      sqlNum(v.donorTotalGiving ?? null),
    ];
    const suffix = i < DEMO_VOLUNTEERS.length - 1 ? "," : "";
    return `  (${parts.join(", ")})${suffix}`;
  });

  lines.push(...volunteerRows);
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET",
    "  name = EXCLUDED.name,",
    "  email = EXCLUDED.email,",
    "  skills = EXCLUDED.skills,",
    "  availability = EXCLUDED.availability,",
    "  total_hours = EXCLUDED.total_hours,",
    "  joined_date = EXCLUDED.joined_date,",
    "  is_also_donor = EXCLUDED.is_also_donor,",
    "  donor_total_giving = EXCLUDED.donor_total_giving,",
    "  updated_at = now();",
    ""
  );

  lines.push(
    "INSERT INTO public.nonprofit_volunteer_shifts (",
    "  id, volunteer_id, event_name, date, hours, status",
    ") VALUES"
  );

  const shiftRows: string[] = [];
  for (const v of DEMO_VOLUNTEERS) {
    for (const s of v.shifts) {
      shiftRows.push(
        `  ('${seedUuid(s.id)}', '${seedUuid(v.id)}', ${sqlStr(s.eventName)}, ${sqlStr(parseDemoDate(s.date, s.id))}, ${sqlNum(s.hours)}, ${sqlStr(s.status)})`
      );
    }
  }
  lines.push(shiftRows.join(",\n"));
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET",
    "  volunteer_id = EXCLUDED.volunteer_id,",
    "  event_name = EXCLUDED.event_name,",
    "  date = EXCLUDED.date,",
    "  hours = EXCLUDED.hours,",
    "  status = EXCLUDED.status,",
    "  updated_at = now();",
    ""
  );

  return lines.join("\n");
}

function generateDonationsSql(): string {
  const campaignIds = DEMO_CAMPAIGNS.map((c) => seedUuid(c.id));
  const donationIds = DEMO_DONATIONS_RECENT.map((d) => seedUuid(d.id));

  const lines: string[] = [
    fileHeader("Nonprofit Campaigns + Donations"),
    `DELETE FROM public.nonprofit_donations WHERE id IN (${donationIds.map((id) => `'${id}'`).join(", ")});`,
    `DELETE FROM public.nonprofit_campaigns WHERE id IN (${campaignIds.map((id) => `'${id}'`).join(", ")});`,
    "",
    "INSERT INTO public.nonprofit_campaigns (",
    "  id, created_by, name, description, goal, raised, donor_count, start_date, end_date, is_active, fund_designation",
    ") VALUES",
  ];

  const campaignRows = DEMO_CAMPAIGNS.map((c, i) => {
    const parts = [
      `'${seedUuid(c.id)}'`,
      "(SELECT id FROM auth.users ORDER BY created_at LIMIT 1)",
      sqlStr(c.name),
      sqlStr(c.description),
      sqlNum(c.goal),
      sqlNum(c.raised),
      sqlNum(c.donorCount),
      sqlStr(parseDemoDate(c.startDate, c.id)),
      c.endDate ? sqlStr(parseDemoDate(c.endDate, c.id)) : "NULL",
      sqlBool(c.isActive),
      sqlStr(c.fundDesignation),
    ];
    const suffix = i < DEMO_CAMPAIGNS.length - 1 ? "," : "";
    return `  (${parts.join(", ")})${suffix}`;
  });

  lines.push(...campaignRows);
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET",
    "  name = EXCLUDED.name,",
    "  description = EXCLUDED.description,",
    "  goal = EXCLUDED.goal,",
    "  raised = EXCLUDED.raised,",
    "  donor_count = EXCLUDED.donor_count,",
    "  start_date = EXCLUDED.start_date,",
    "  end_date = EXCLUDED.end_date,",
    "  is_active = EXCLUDED.is_active,",
    "  fund_designation = EXCLUDED.fund_designation,",
    "  updated_at = now();",
    ""
  );

  lines.push(
    "INSERT INTO public.nonprofit_donations (",
    "  id, campaign_id, donor_name, donor_email, amount, frequency, fund_designation, is_anonymous, payment_method, created_at",
    ") VALUES"
  );

  const donationRows = DEMO_DONATIONS_RECENT.map((d, i) => {
    const parts = [
      `'${seedUuid(d.id)}'`,
      `'${seedUuid(d.campaignId)}'`,
      sqlStr(d.donorName),
      "NULL",
      sqlNum(d.amount),
      sqlStr(d.frequency),
      sqlStr(d.fundDesignation),
      sqlBool(d.isAnonymous),
      sqlStr(d.paymentMethod),
      `'${parseDemoTimestamp(d.date, d.id)}'`,
    ];
    const suffix = i < DEMO_DONATIONS_RECENT.length - 1 ? "," : "";
    return `  (${parts.join(", ")})${suffix}`;
  });

  lines.push(...donationRows);
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET",
    "  campaign_id = EXCLUDED.campaign_id,",
    "  donor_name = EXCLUDED.donor_name,",
    "  amount = EXCLUDED.amount,",
    "  frequency = EXCLUDED.frequency,",
    "  fund_designation = EXCLUDED.fund_designation,",
    "  is_anonymous = EXCLUDED.is_anonymous,",
    "  payment_method = EXCLUDED.payment_method,",
    "  created_at = EXCLUDED.created_at,",
    "  updated_at = now();",
    ""
  );

  return lines.join("\n");
}

function generateEventsSql(): string {
  const eventIds = DEMO_MANAGED_EVENTS.map((e) => seedUuid(e.id));
  const ticketIds: string[] = [];
  const speakerIds: string[] = [];
  const agendaIds: string[] = [];
  const registrantIds: string[] = [];

  for (const e of DEMO_MANAGED_EVENTS) {
    e.ticketTypes.forEach((t, i) => ticketIds.push(seedUuid(`${e.id}:ticket:${i}:${t.tier}`)));
    e.speakers.forEach((s, i) => speakerIds.push(seedUuid(`${e.id}:speaker:${i}:${s.name}`)));
    e.agenda.forEach((a, i) => agendaIds.push(seedUuid(`${e.id}:agenda:${i}:${a.time}`)));
    e.registrants.forEach((r) => registrantIds.push(seedUuid(r.id)));
  }

  const lines: string[] = [
    fileHeader("Nonprofit Events (lifecycle)"),
    `DELETE FROM public.nonprofit_event_registrants WHERE id IN (${registrantIds.map((id) => `'${id}'`).join(", ")});`,
    `DELETE FROM public.nonprofit_event_agenda_items WHERE id IN (${agendaIds.map((id) => `'${id}'`).join(", ")});`,
    `DELETE FROM public.nonprofit_event_speakers WHERE id IN (${speakerIds.map((id) => `'${id}'`).join(", ")});`,
    `DELETE FROM public.nonprofit_event_ticket_types WHERE id IN (${ticketIds.map((id) => `'${id}'`).join(", ")});`,
    `DELETE FROM public.nonprofit_events WHERE id IN (${eventIds.map((id) => `'${id}'`).join(", ")});`,
    "",
    "INSERT INTO public.nonprofit_events (",
    "  id, created_by, title, status, date, location, description, capacity, fund_raised",
    ") VALUES",
  ];

  const eventRows = DEMO_MANAGED_EVENTS.map((e, i) => {
    const parts = [
      `'${seedUuid(e.id)}'`,
      "(SELECT id FROM auth.users ORDER BY created_at LIMIT 1)",
      sqlStr(e.title),
      sqlStr(e.status),
      sqlStr(parseDemoDate(e.date, e.id)),
      sqlStr(e.location),
      sqlStr(e.description),
      sqlNum(e.capacity),
      e.fundRaised != null ? sqlNum(e.fundRaised) : "NULL",
    ];
    const suffix = i < DEMO_MANAGED_EVENTS.length - 1 ? "," : "";
    return `  (${parts.join(", ")})${suffix}`;
  });

  lines.push(...eventRows);
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET",
    "  title = EXCLUDED.title,",
    "  status = EXCLUDED.status,",
    "  date = EXCLUDED.date,",
    "  location = EXCLUDED.location,",
    "  description = EXCLUDED.description,",
    "  capacity = EXCLUDED.capacity,",
    "  fund_raised = EXCLUDED.fund_raised,",
    "  updated_at = now();",
    ""
  );

  // Ticket types
  lines.push(
    "INSERT INTO public.nonprofit_event_ticket_types (",
    "  id, event_id, tier, price, capacity, sold",
    ") VALUES"
  );
  const ticketRows: string[] = [];
  for (const e of DEMO_MANAGED_EVENTS) {
    e.ticketTypes.forEach((t, i) => {
      ticketRows.push(
        `  ('${seedUuid(`${e.id}:ticket:${i}:${t.tier}`)}', '${seedUuid(e.id)}', ${sqlStr(t.tier)}, ${sqlNum(t.price)}, ${sqlNum(t.capacity)}, ${sqlNum(t.sold)})`
      );
    });
  }
  lines.push(ticketRows.join(",\n"));
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET",
    "  tier = EXCLUDED.tier,",
    "  price = EXCLUDED.price,",
    "  capacity = EXCLUDED.capacity,",
    "  sold = EXCLUDED.sold;",
    ""
  );

  // Speakers
  const speakerRows: string[] = [];
  for (const e of DEMO_MANAGED_EVENTS) {
    e.speakers.forEach((s, i) => {
      speakerRows.push(
        `  ('${seedUuid(`${e.id}:speaker:${i}:${s.name}`)}', '${seedUuid(e.id)}', ${sqlStr(s.name)}, ${sqlStr(s.title)}, ${sqlStr(s.organization)}, ${i})`
      );
    });
  }
  if (speakerRows.length > 0) {
    lines.push(
      "INSERT INTO public.nonprofit_event_speakers (",
      "  id, event_id, name, title, bio, display_order",
      ") VALUES"
    );
    lines.push(speakerRows.join(",\n"));
    lines.push(
      "ON CONFLICT (id) DO UPDATE SET",
      "  name = EXCLUDED.name,",
      "  title = EXCLUDED.title,",
      "  bio = EXCLUDED.bio,",
      "  display_order = EXCLUDED.display_order;",
      ""
    );
  }

  // Agenda
  lines.push(
    "INSERT INTO public.nonprofit_event_agenda_items (",
    "  id, event_id, time, title, speaker_name, display_order",
    ") VALUES"
  );
  const agendaRows: string[] = [];
  for (const e of DEMO_MANAGED_EVENTS) {
    e.agenda.forEach((a, i) => {
      agendaRows.push(
        `  ('${seedUuid(`${e.id}:agenda:${i}:${a.time}`)}', '${seedUuid(e.id)}', ${sqlStr(a.time)}, ${sqlStr(a.title)}, ${sqlStr(a.speaker ?? null)}, ${i})`
      );
    });
  }
  lines.push(agendaRows.join(",\n"));
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET",
    "  time = EXCLUDED.time,",
    "  title = EXCLUDED.title,",
    "  speaker_name = EXCLUDED.speaker_name,",
    "  display_order = EXCLUDED.display_order;",
    ""
  );

  // Registrants
  lines.push(
    "INSERT INTO public.nonprofit_event_registrants (",
    "  id, event_id, name, email, ticket_tier, checked_in, registered_at",
    ") VALUES"
  );
  const registrantRows: string[] = [];
  for (const e of DEMO_MANAGED_EVENTS) {
    for (const r of e.registrants) {
      registrantRows.push(
        `  ('${seedUuid(r.id)}', '${seedUuid(e.id)}', ${sqlStr(r.name)}, ${sqlStr(r.email)}, ${sqlStr(r.ticketTier)}, ${sqlBool(r.checkedIn)}, '${parseDemoTimestamp(r.registeredDate, r.id)}')`
      );
    }
  }
  lines.push(registrantRows.join(",\n"));
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET",
    "  name = EXCLUDED.name,",
    "  email = EXCLUDED.email,",
    "  ticket_tier = EXCLUDED.ticket_tier,",
    "  checked_in = EXCLUDED.checked_in,",
    "  registered_at = EXCLUDED.registered_at;",
    ""
  );

  return lines.join("\n");
}

function generateProgramsSql(): string {
  const ids = DEMO_PROGRAMS.map((p) => seedUuid(p.id));
  const lines: string[] = [
    fileHeader("Nonprofit Programs"),
    `DELETE FROM public.nonprofit_programs WHERE id IN (${ids.map((id) => `'${id}'`).join(", ")});`,
    "",
    "INSERT INTO public.nonprofit_programs (",
    "  id, created_by, name, description, start_date, status, lead_staff,",
    "  beneficiary_count, volunteer_hours, budget_used, budget_total, outcomes_achieved, outcomes_target",
    ") VALUES",
  ];

  const rows = DEMO_PROGRAMS.map((p, i) => {
    const m = p.metrics;
    const parts = [
      `'${seedUuid(p.id)}'`,
      "(SELECT id FROM auth.users ORDER BY created_at LIMIT 1)",
      sqlStr(p.name),
      sqlStr(p.description),
      sqlStr(parseDemoDate(p.startDate, p.id)),
      sqlStr(p.status),
      sqlStr(p.leadStaff),
      sqlNum(m.beneficiaryCount),
      sqlNum(m.volunteerHours),
      sqlNum(m.budgetUsed),
      sqlNum(m.budgetTotal),
      sqlNum(m.outcomesAchieved),
      sqlNum(m.outcomesTarget),
    ];
    const suffix = i < DEMO_PROGRAMS.length - 1 ? "," : "";
    return `  (${parts.join(", ")})${suffix}`;
  });

  lines.push(...rows);
  lines.push(
    "ON CONFLICT (id) DO UPDATE SET",
    "  name = EXCLUDED.name,",
    "  description = EXCLUDED.description,",
    "  start_date = EXCLUDED.start_date,",
    "  status = EXCLUDED.status,",
    "  lead_staff = EXCLUDED.lead_staff,",
    "  beneficiary_count = EXCLUDED.beneficiary_count,",
    "  volunteer_hours = EXCLUDED.volunteer_hours,",
    "  budget_used = EXCLUDED.budget_used,",
    "  budget_total = EXCLUDED.budget_total,",
    "  outcomes_achieved = EXCLUDED.outcomes_achieved,",
    "  outcomes_target = EXCLUDED.outcomes_target,",
    "  updated_at = now();",
    ""
  );
  return lines.join("\n");
}

const files: Record<string, string> = {
  "10-nonprofit-members.sql": generateMembersSql(),
  "11-nonprofit-volunteers.sql": generateVolunteersSql(),
  "12-nonprofit-donations.sql": generateDonationsSql(),
  "13-nonprofit-events.sql": generateEventsSql(),
  "14-nonprofit-programs.sql": generateProgramsSql(),
};

export function writeNonprofitSeedFiles(): void {
  for (const [name, content] of Object.entries(files)) {
    const path = join(SEED_DIR, name);
    writeFileSync(path, content, "utf8");
    console.log(`Wrote ${path}`);
  }
}

const isMain =
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
  writeNonprofitSeedFiles();
  console.log("Done. Run npm run seed:nonprofit to apply.");
}
